export const FETCHING_PRODUCTS_INIT = "FETCHING_PRODUCTS_INIT";
export const FETCHING_PRODUCTS_SUCCESS = "FETCHING_PRODUCTS_SUCCESS";
export const FETCHING_PRODUCTS_ERROR = "FETCHING_PRODUCTS_ERROR";
export const FETCHING_CATEGORIES_INIT = "FETCHING_CATEGORIES_INIT";
export const FETCHING_CATEGORIES_SUCCESS = "FETCHING_CATEGORIES_SUCCESS";
export const FETCHING_CATEGORIES_ERROR = "FETCHING_CATEGORIES_ERROR";
export const SAVE_CATEGORY_ID = "SAVE_CATEGORY_ID";
export const FILTER_BY_CATEGORY = "FILTER_BY_CATEGORY";
